-- DIMENSIONS EXPLORATION

--EXPLORE ALL COUNTRIES OUR CUSTOMERS FROM

SELECT DISTINCT country FROM gold.dim_customers

-- EXPLORE ALL CATEGORIES "THE MAJOR DIVISION"

SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3
